# Nom de l'application
spring.application.name=newgen-tgv-backend

# Profil actif par defaut
spring.profiles.active=dev

# Configuration du serveur
server.port=${PORT:8080}

# Activation des Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# RFC 7807 Problem Details
spring.mvc.problemdetails.enabled=true

# SpringDoc OpenAPI & Swagger UI Configuration
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
